server:
  port:

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name:
    url:
    username:
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
  
  servlet:
    multipart:
      max-file-size:
      max-request-size:

  # JPA settings
  jpa:
    hibernate:
      ddl-auto:
    properties:
      show-sql:
      hibernate:
        format_sql:

logging:
  level:
    org.hibernate.SQL:
    org.hibernate.type:

  # AWS Account Credentials

cloud:
  aws:
    credentials:
      access-key:
      secret-key:

  # AWS S3 bucket Info
    s3:
      bucket:

    region:
      static:
    stack:
      auto:

jwt:
  secret:
    access:
    refresh:
  time:
    access:
    refresh:

fcm:
  secret:
    time:
    day: